# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import payment_system_pb2 as payment__system__pb2


class PaymentSystemStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.QueryToCommit = channel.unary_unary(
                '/PaymentSystem.PaymentSystem/QueryToCommit',
                request_serializer=payment__system__pb2.QueryRequest.SerializeToString,
                response_deserializer=payment__system__pb2.Response.FromString,
                )


class PaymentSystemServicer(object):
    """Missing associated documentation comment in .proto file."""

    def QueryToCommit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PaymentSystemServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'QueryToCommit': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryToCommit,
                    request_deserializer=payment__system__pb2.QueryRequest.FromString,
                    response_serializer=payment__system__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'PaymentSystem.PaymentSystem', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PaymentSystem(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def QueryToCommit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/PaymentSystem.PaymentSystem/QueryToCommit',
            payment__system__pb2.QueryRequest.SerializeToString,
            payment__system__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
