# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import transaction_verification_pb2 as transaction__verification__pb2


class VerificationServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Initialize = channel.unary_unary(
                '/verification.VerificationService/Initialize',
                request_serializer=transaction__verification__pb2.VerificationRequest.SerializeToString,
                response_deserializer=transaction__verification__pb2.VerificationResponse.FromString,
                )
        self.VerifyNotEmpty = channel.unary_unary(
                '/verification.VerificationService/VerifyNotEmpty',
                request_serializer=transaction__verification__pb2.VerificationRequest.SerializeToString,
                response_deserializer=transaction__verification__pb2.VerificationResponse.FromString,
                )
        self.VerifyUserData = channel.unary_unary(
                '/verification.VerificationService/VerifyUserData',
                request_serializer=transaction__verification__pb2.VerificationRequest.SerializeToString,
                response_deserializer=transaction__verification__pb2.VerificationResponse.FromString,
                )
        self.VerifyCreditCard = channel.unary_unary(
                '/verification.VerificationService/VerifyCreditCard',
                request_serializer=transaction__verification__pb2.VerificationRequest.SerializeToString,
                response_deserializer=transaction__verification__pb2.VerificationResponse.FromString,
                )


class VerificationServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Initialize(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerifyNotEmpty(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerifyUserData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerifyCreditCard(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VerificationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Initialize': grpc.unary_unary_rpc_method_handler(
                    servicer.Initialize,
                    request_deserializer=transaction__verification__pb2.VerificationRequest.FromString,
                    response_serializer=transaction__verification__pb2.VerificationResponse.SerializeToString,
            ),
            'VerifyNotEmpty': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifyNotEmpty,
                    request_deserializer=transaction__verification__pb2.VerificationRequest.FromString,
                    response_serializer=transaction__verification__pb2.VerificationResponse.SerializeToString,
            ),
            'VerifyUserData': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifyUserData,
                    request_deserializer=transaction__verification__pb2.VerificationRequest.FromString,
                    response_serializer=transaction__verification__pb2.VerificationResponse.SerializeToString,
            ),
            'VerifyCreditCard': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifyCreditCard,
                    request_deserializer=transaction__verification__pb2.VerificationRequest.FromString,
                    response_serializer=transaction__verification__pb2.VerificationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'verification.VerificationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class VerificationService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Initialize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/verification.VerificationService/Initialize',
            transaction__verification__pb2.VerificationRequest.SerializeToString,
            transaction__verification__pb2.VerificationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def VerifyNotEmpty(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/verification.VerificationService/VerifyNotEmpty',
            transaction__verification__pb2.VerificationRequest.SerializeToString,
            transaction__verification__pb2.VerificationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def VerifyUserData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/verification.VerificationService/VerifyUserData',
            transaction__verification__pb2.VerificationRequest.SerializeToString,
            transaction__verification__pb2.VerificationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def VerifyCreditCard(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/verification.VerificationService/VerifyCreditCard',
            transaction__verification__pb2.VerificationRequest.SerializeToString,
            transaction__verification__pb2.VerificationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
